#!/bin/bash

usage () {
	cat <<- FIN >&2
	ExRead 1.0: read of an excel sheet
	Thu Apr 24 01:19:09 JST 2014

	Copyright (C) 2014 Ryuichi UEDA

	usage: exread-sheet <sheet> original.xlsx
	FIN

	exit 1
}

dir=$(dirname $0)

[ "$1" = "-h" ] && usage
[ "$1" = "--help" ] && usage

$dir/exread-sheet "$1" "$2"				|
awk '$3=="s"'						|
maezero 4.10						|
sort -k4,4n						|
join1 key=4 <($dir/exread-str "$2" | maezero 1.10) -	|
sed 's/ s [0-9][0-9]*//'
[ "$(echo ${PIPESTATUS[@]} | tr -d '0 ')" = "" ] || exit 1

$dir/exread-sheet "$1" "$2"				|
awk '$3!="s"{print $1,$2,$4}'
[ "$(echo ${PIPESTATUS[@]} | tr -d '0 ')" = "" ] || exit 1

exit 0
#The MIT License
#
#Copyright (C) Ryuichi UEDA
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
