#!/bin/bash

usage () {
	cat <<- FIN >&2
	ExRead String 1.0: read of an excel string sheet
	Thu Apr 24 01:04:10 JST 2014

	Copyright (C) 2014 Ryuichi UEDA

	usage: exread original.xlsx
	FIN

	exit 1
}

[ "$1" = "-h" ] && usage
[ "$1" = "--help" ] && usage

unzip -p "$1" "xl/sharedStrings.xml"	|
grep -o '<si><t>[^<]*</t>'		|
sed 's;<si><t>;;'			|
sed 's;</t>;;'				|
awk '{print NR-1,$0}'
[ "$(echo ${PIPESTATUS[@]} | tr -d '0 ')" = "" ] || exit 1

exit 0
#The MIT License
#
#Copyright (C) Ryuichi UEDA
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
