#!/bin/bash
# wordsed: a string replacement tool for docx
# written by Ryuichi UEDA, Apr. 22, 2014 
# usage: cat original.docx | wordsed <sed command> > newfile.docx

tmp=./tmp-exshell-$$
error () {
	[ -d "$tmp" ] && rm -Rf "$tmp" && exit 1
	cd - && [ -d "$tmp" ] && rm -Rf "$tmp"
	exit 1
}

trap error 1 2 3 15

mkdir "$tmp"                             &&
cd "$tmp"                                &&
cat < /dev/stdin > "tmp.zip"             &&
unzip "tmp.zip" >&2                      &&
rm "tmp.zip"                             &&
sed "$1" word/document.xml > tmp         &&
mv tmp word/document.xml                 &&
zip -r tmp.docx * >&2                    &&
cat tmp.docx                             &&
cd - >&2                                 &&
rm -Rf "$tmp"    || error

#The MIT License
#
#Copyright (C) Ryuichi UEDA
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
